config/routes.rb
Rails.application.routes.draw do
    resources :produtos_compras
    resources :categorias_produtos

    resources :compras do
        collection do
            get 'minhas_compras'
            get 'checkout'
            get 'relatorio'
            post 'cart_save'
            get 'buscar_diario'
            get 'buscar_cliente'
            match 'atualizar_status', via: [:get, :post]
        end
    end

    # post '/compras/cart_save', to: 'compras#cart_save'

    resources :categorias

    resources :produtos do
        collection do
            get 'catalogo'
            match 'view', via: [:get, :post]
        end
    end

    resources :clientes do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
        end
    end
    resources :admins do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
            get 'private_route'
        end
    end

    devise_for :usuarios

    root to: 'produtos#catalogo'
end

app/models/cliente.rb
class Cliente < ApplicationRecord
  belongs_to :usuario
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
    before_action :validate_route

    def index
        @clientes = Cliente.all
    end

    # GET /clientes/new
    def new
        @cliente = Cliente.new
    end

    def view
        @cliente = Usuario.find_by(email: params[:email])
	end

    def criar
        respond_to do |format|
            if Usuario.verificar_email(params[:email])
                usuario = Usuario.invite!(:email => params[:email], :nome => params[:nome])

                flash[:notice] =  'Convite enviado com sucesso!'
                format.js {render inline: "location.href='/clientes/view?email=#{params[:email]}'"}
            else
                flash[:notice] =  'Email já cadastrado no sistema.'
                format.js {render inline: "location.reload();" }
            end
        end
    end

    def editar
		@cliente = Usuario.find_by(email: params[:email])
	end

    def atualizar
		@cliente = Usuario.find_by(email: params[:email])
		if !params[:senha].blank?
			@cliente.update(nome: params[:nome], password: params[:senha])
		else
			@cliente.update(nome: params[:nome])
		end

    	respond_to do |format|
     		flash[:notice] =  'Cliente atualizado com sucesso!'
			format.js {render inline: "location.href='/clientes/view?email=#{params[:email]}'"}
		end
	end

    def destroy
        @usuario = Usuario.find_by(email: params[:email])

        @cliente = Cliente.find_by(usuario_id: @usuario)


        @compras = Compra.where(cliente_id: @cliente.id)

        @compras.each do |compra|
            @produtos_compras = ProdutosCompra.where(compra_id: compra.id)

            @produtos_compras.each do |produtos_compra|
                produtos_compra.destroy
            end

            compra.destroy
        end

        @cliente.destroy
        @usuario.destroy

        respond_to do |format|
        format.html { redirect_to clientes_url, notice: 'Cliente deletado com sucesso.' }
        format.json { head :no_content }
        end
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/editar.html.erb
<div class="form-container -cliente">
    <div class="wrapper">
        <div class="heading">
            <h1 class="legend">Editando cliente</h1>
        </div>

        <%= form_with(url: "/clientes/atualizar", method: "get", class: "form-register") do |f| %>
            <div class="block -cliente">
                <fieldset class="fieldset -name">
                    <%= f.label :nome, "Nome", class: "label" %>
                    <%= f.text_field :nome, value: @cliente.nome, class: "input", name: "nome", id: "nome", :required => true %>
                </fieldset>

                <fieldset class="fieldset -email">
                    <%= f.label :email, "Email", class: "label" %>
                    <%= f.text_field :email, value: @cliente.email, class: "input", name: "email", id: "email", :required => true %>
                </fieldset>

                <fieldset class="fieldset -password">
                    <%= f.label :senha, "Senha", class: "label" %>
                    <%= f.password_field :senha, class: "input", name: "senha", id: "senha" %>
                </fieldset>
            </div>

            <div class="actions">
                <%= f.submit "Salvar", class: "action -save" %>
            </div>
        <% end %>

        <div class="actions">
            <%= link_to 'Ver cliente', view_clientes_path(email: @cliente.email), class: "action -show" %>
            <%= link_to '<i class="fas fa-reply"></i> Voltar'.html_safe, clientes_path, class: "action -back" %>
        </div>
    </div>
</div>

app/views/clientes/index.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="container-info -clientes">
  <div class="heading">
      <h1 class="title">Clientes</h1>
  </div>

  <div class="wrapper">
      <div class="info-table -clientes">
          <table class="table">
              <thead>
                  <tr class="table-heading">
                      <th class="item -name">Nome</th>
                      <th class="item -email">Email</th>
                      <th class="item -actions"></th>
                      <th></th>
                  </tr>
              </thead>

              <tbody class="table-info">
                <% @clientes.each do |cliente| %>
                  <tr class="list">
                      <td class="item -name" data-th="Nome"><%= cliente.usuario.nome %></td>
                      <td class="item -email" data-th="Email"><%= cliente.usuario.email %></td>
                      <td class="actions" data-th="Ações">
                          <%= link_to 'Ver', view_clientes_path(email: cliente.usuario.email), class: "action -underlined -view" %>
                          <%= link_to 'Editar', editar_clientes_path(email: cliente.usuario.email), class: "action -underlined -edit" %>
                          <%= link_to 'Apagar', excluir_clientes_path(email: cliente.usuario.email), method: :delete, data: { confirm: 'Você tem certeza?' }, class: "action -underlined -delete" %>
                      </td>
                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>

      <%= link_to '<i class="fa fa-plus"></i> Novo cliente'.html_safe, new_cliente_path, class: "action -new" %>
  </div>
</div>

app/views/clientes/new.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="form-container -cliente">
    <div class="wrapper">
        <div class="heading">
            <h1 class="legend">Cadastro de cliente</h1>
            <p class="note">Cadastre um cliente na loja e ele recebe um email de confirmação de cadastro</p>
        </div>

        <%= form_with(url: "/clientes/criar", method: "get", class: "form-register") do |f| %>
            <div class="block -admin">
                <fieldset class="fieldset -name">
                    <%= f.label :nome, "Nome", class: "label" %>
                    <%= f.text_field :nome, class: "input", name: "nome", id: "nome", :required => true %>
                </fieldset>

                <fieldset class="fieldset -email">
                    <%= f.label :email, "Email", class: "label" %>
                    <%= f.text_field :email, class: "input", name: "email", id: "email", :required => true %>
                </fieldset>
            </div>

            <div class="actions">
                <%= f.submit "Salvar", class: "action -save" %>
            </div>
        <% end %>

        <div class="actions">
            <%= link_to '<i class="fas fa-reply"></i> Voltar'.html_safe, clientes_path, class: "action -back" %>
        </div>
    </div>
</div>

app/views/clientes/view.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="info-container -admin">
	<div class="heading">
		<h1 class="title">Cliente</h1>
	</div>

	<div class="wrapper">
		<div class="info-box -admin">
			<div class="content">
        <p class="item -name"><strong>Nome:</strong> <%= @cliente.nome %></p>
        <p class="item -email"><strong>Email:</strong> <%= @cliente.email %></p>
			</div>
			<div class="actions">
				<%= link_to 'Editar', editar_clientes_path(email: @cliente.email), class: "action -underlined -edit" %>
				<%= link_to 'Voltar', clientes_path, class: "action -underlined -back" %>
			</div>
		</div>
	</div>
</div>