config/routes.rb
Rails.application.routes.draw do
    resources :produtos_compras
    resources :categorias_produtos

    resources :compras do
        collection do
            get 'minhas_compras'
            get 'checkout'
            get 'relatorio'
            post 'cart_save'
            get 'buscar_diario'
            get 'buscar_cliente'
            match 'atualizar_status', via: [:get, :post]
        end
    end

    # post '/compras/cart_save', to: 'compras#cart_save'

    resources :categorias

    resources :produtos do
        collection do
            get 'catalogo'
            match 'view', via: [:get, :post]
        end
    end

    resources :clientes do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
        end
    end
    resources :admins do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
            get 'private_route'
        end
    end

    devise_for :usuarios

    root to: 'produtos#catalogo'
end

app/views/admins/editar.html.erb
<div class="form-container -admin">
    <div class="wrapper">
        <div class="heading">
            <h1 class="legend">Editando administrador</h1>
        </div>

        <%= form_with(url: "/admins/atualizar", method: "get", class: "form-register") do |f| %>
            <div class="block -admin">
                <fieldset class="fieldset -name">
                    <%= f.label :nome, "Nome", class: "label" %>
                    <%= f.text_field :nome, value: @admin.nome, class: "input", name: "nome", id: "nome", :required => true %>
                </fieldset>

                <fieldset class="fieldset -email">
                    <%= f.label :email, "Email", class: "label" %>
                    <%= f.text_field :email, value: @admin.email, class: "input", name: "email", id: "email", :required => true %>
                </fieldset>

                <fieldset class="fieldset -password">
                    <%= f.label :senha, "Senha", class: "label" %>
                    <%= f.password_field :senha, class: "input", name: "senha", id: "senha" %>
                </fieldset>
            </div>

            <div class="actions">
                <%= f.submit "Salvar", class: "action -save" %>
            </div>
        <% end %>

        <div class="actions">
            <%= link_to 'Ver admin', view_admins_path(email: @admin.email), class: "action -show" %>
            <%= link_to '<i class="fas fa-reply"></i> Voltar'.html_safe, admins_path, class: "action -back" %>
        </div>
    </div>
</div>

app/views/admins/index.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="container-info -admins">
  <div class="heading">
      <h1 class="title">Administradores</h1>
  </div>

  <div class="wrapper">
      <div class="info-table -admins">
          <table class="table">
              <thead>
                  <tr class="table-heading">
                      <th class="item -name">Nome</th>
                      <th class="item -email">Email</th>
                      <th class="item -actions"></th>
                      <th></th>
                  </tr>
              </thead>

              <tbody class="table-info">
                <% @admins.each do |admin| %>
                  <tr class="list">
                      <td class="item -name" data-th="Nome"><%= admin.usuario.nome %></td>
                      <td class="item -email" data-th="Email"><%= admin.usuario.email %></td>
                      <td class="actions" data-th="Ações">
                          <%= link_to 'Ver', view_admins_path(email: admin.usuario.email), class: "action -underlined -view" %>
                          <%= link_to 'Editar', editar_admins_path(email: admin.usuario.email), class: "action -underlined -edit" %>
                          <%= link_to 'Apagar', excluir_admins_path(email: admin.usuario.email), method: :delete, data: { confirm: 'Você tem certeza?' }, class: "action -underlined -delete" %>
                      </td>
                  </tr>
                <% end %>
              </tbody>
          </table>
      </div>

      <%= link_to '<i class="fa fa-plus"></i> Novo admin'.html_safe, new_admim_path, class: "action -new" %>
  </div>
</div>

app/views/admins/new.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="form-container -admin">
    <div class="wrapper">
        <div class="heading">
            <h1 class="legend">Cadastro de administrador</h1>
            <p class="note">Convide um usuário para ser administrador da loja</p>
        </div>

        <%= form_with(url: "/admins/criar", method: "post", class: "form-register") do |f| %>
            <div class="block -admin">
                <fieldset class="fieldset -name">
                    <%= f.label :nome, "Nome", class: "label" %>
                    <%= f.text_field :nome, class: "input", name: "nome", id: "nome", :required => true %>
                </fieldset>

                <fieldset class="fieldset -email">
                    <%= f.label :email, "Email", class: "label" %>
                    <%= f.text_field :email, class: "input", name: "email", id: "email", :required => true %>
                </fieldset>
            </div>

            <div class="actions">
                <%= f.submit "Salvar", class: "action -save" %>
            </div>
        <% end %>

        <div class="actions">
            <%= link_to '<i class="fas fa-reply"></i> Voltar'.html_safe, admins_path, class: "action -back" %>
        </div>
    </div>
</div>

app/views/admins/private_route.html.erb
<div class="private-wrapper">
	<div class="content">
		<i class="fa fa-exclamation-triangle"></i>
		<h1 class="title">
            Rota privada
        </h1>
		<p class="description">
            O acesso a essa página só é permitido para administradores
        </p>

		<%= link_to '<i class="fas fa-reply"></i> Voltar para a página inicial'.html_safe, root_path, class: "action -back" %>
	</div>

</div>

app/views/admins/view.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="info-container -admin">
	<div class="heading">
		<h1 class="title">Administrador</h1>
	</div>

	<div class="wrapper">
		<div class="info-box -admin">
			<div class="content">
        <p class="item -name"><strong>Nome:</strong> <%= @admin.nome %></p>
        <p class="item -email"><strong>Email:</strong> <%= @admin.email %></p>
			</div>
			<div class="actions">
				<%= link_to 'Editar', editar_admins_path(email: @admin.email), class: "action -underlined -edit" %>
				<%= link_to 'Voltar', admins_path, class: "action -underlined -back" %>
			</div>
		</div>
	</div>
</div>