config/routes.rb
Rails.application.routes.draw do
    resources :produtos_compras
    resources :categorias_produtos

    resources :compras do
        collection do
            get 'minhas_compras'
            get 'checkout'
            get 'relatorio'
            post 'cart_save'
            get 'buscar_diario'
            get 'buscar_cliente'
            match 'atualizar_status', via: [:get, :post]
        end
    end

    # post '/compras/cart_save', to: 'compras#cart_save'

    resources :categorias

    resources :produtos do
        collection do
            get 'catalogo'
            match 'view', via: [:get, :post]
        end
    end

    resources :clientes do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
        end
    end
    resources :admins do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
            get 'private_route'
        end
    end

    devise_for :usuarios

    root to: 'produtos#catalogo'
end

app/models/compra.rb
class Compra < ApplicationRecord
    belongs_to :cliente
    has_many :produtos_compras

    validates_presence_of :cliente, :data, :hora, :cep, :endereco, :bairro, :cidade, :estado, :forma_pagamento, :valor_total, :status
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
    before_action :validate_route, only: [:index, :edit, :new]
    before_action :set_compra, only: [:show, :edit, :update, :destroy]

    # GET /compras
    # GET /compras.json
    def index
        @compras = Compra.all.order(data: :desc)
    end

    def minhas_compras
        cliente = Cliente.find_by(usuario_id: current_usuario.id)
        @compras = Compra.where(cliente_id: cliente.id).order(data: :desc)
    end

    def cart_save
        produtos_string = request.raw_post
        produtos_json = JSON.parse(produtos_string)

        cliente = Cliente.find_by(usuario_id: current_usuario.id)

        co = ComprasProdutosCliente.where(cliente_id: cliente.id)
        co.delete_all if !produtos_json.blank?

        produtos_json.each do |produto_ind|
            produto = Produto.find(produto_ind.select{ |k,val| k == 'produto' }.values.first)
            qtde = produto_ind.select{ |k,val| k == 'qtde' }.values.first
            compra_produto_cliente = ComprasProdutosCliente.new cliente_id: cliente.id, produto_id: produto.id, quantidade: qtde
            compra_produto_cliente.save
        end
    end

    def checkout
        @compra = Compra.new
        @produtos = get_produtos
    end

    def relatorio
        @compras_diario = Compra.group(:data).select("sum(valor_total), data").where('data BETWEEN ? AND ?', Date.today, Date.today).order("data DESC").sum(:valor_total)

        @compras_cliente = Compra.group("compras.cliente_id").select("compras.cliente_id").where('data BETWEEN ? AND ?', Date.today, Date.today).order("COUNT(compras.cliente_id) DESC").count("compras.cliente_id")
    end

    def buscar_diario
        if params[:data_inicio].blank? || params[:data_fim].blank?
            @compras_diario = Compra.all
        else
            @compras_diario = Compra.group(:data).select("sum(valor_total), data").where('data BETWEEN ? AND ?', params[:data_inicio], params[:data_fim]).order("data DESC").sum(:valor_total)
        end

        render :inline => render_to_string(:partial => 'relatorio_diario')
    end

    def buscar_cliente
        if params[:data_inicio].blank? || params[:data_fim].blank?
            @compras_cliente = Compra.all
        else
            @compras_cliente = Compra.group("compras.cliente_id").select("compras.cliente_id").where('data BETWEEN ? AND ?', params[:data_inicio], params[:data_fim]).order("COUNT(compras.cliente_id) DESC").count("compras.cliente_id")
        end

        render :inline => render_to_string(:partial => 'relatorio_cliente')
    end


    # GET /compras/1
    # GET /compras/1.json
    def show
        @produtos_compras = ProdutosCompra.where(compra_id: params[:id])
    end

    # GET /compras/new
    def new
        @compra = Compra.new
    end

    # GET /compras/1/edit
    def edit
        @produtos = ProdutosCompra.where(compra_id: params[:id])
    end

    # POST /compras
    # POST /compras.json
    def create
        @produtos = get_produtos
        @compra = Compra.new(compra_params)

        if session[:papel_id] == "Administrador"
            cliente = Cliente.find_by(usuario_id: params[:compra][:cliente_id])
            @compra.cliente_id = cliente.id
        end

        @compra.data = Date.today
        @compra.hora = Time.now.strftime("%H:%M:%S")
        @compra.valor_total = params[:compra][:valor_total].to_f
        @compra.status = "Solicitado"

        respond_to do |format|
        if @compra.save
            @produtos.each do |produto|
                ProdutosCompra.create(compra_id: @compra.id, produto_id: produto[:produto][:id], quantidade: produto[:quantidade])
            end
            format.html { redirect_to @compra, notice: 'Compra efetuada com sucesso.' }
            format.json { render :show, status: :created, location: @compra }
        else
            format.html { render :new }
            format.json { render json: @compra.errors, status: :unprocessable_entity }
        end
        end
    end

    def atualizar_status
        @compra = Compra.find(params[:id])
        @compra.update(status: params[:status])

        respond_to do |format|
            format.html { redirect_to @compra, notice: 'Status atualizado com sucesso.' }
            format.json { render :show, status: :ok, location: @compra }
        end
    end

    # PATCH/PUT /compras/1
    # PATCH/PUT /compras/1.json
    def update
        respond_to do |format|
          if @compra.update(compra_params)
            format.html { redirect_to @compra, notice: 'Compra atualizada com sucesso.' }
            format.json { render :show, status: :ok, location: @compra }
          else
            format.html { render :edit }
            format.json { render json: @compra.errors, status: :unprocessable_entity }
          end
        end
    end

    # DELETE /compras/1
    # DELETE /compras/1.json
    def destroy

        @produtos_compras = ProdutosCompra.where(compra_id: @compra.id)
        @produtos_compras.delete_all
        @compra.destroy

        respond_to do |format|
            format.html { redirect_to compras_url, notice: 'Compra deletada com sucesso.' }
            format.json { head :no_content }
        end
    end

    private
    def get_produtos
        cliente = Cliente.find_by(usuario_id: current_usuario.id)

        prod = ComprasProdutosCliente.where(cliente_id: cliente.id).pluck(:produto_id, :quantidade)
        @produtos = []

        prod.each do |produto, qtd|
            @produtos.push({produto: Produto.find(produto), quantidade: qtd })
        end

        return @produtos
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
        @compra = Compra.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def compra_params
        params.require(:compra).permit(:cliente_id, :data, :hora, :cep, :endereco, :bairro, :cidade, :estado, :forma_pagamento, :valor_total, :numero_cartao, :cvv, :data_validade, :status)
    end
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_atualizar_status.html.erb
<div class="container-info -atualizarstatus">
    <div class="wrapper">
        <%= form_tag('/compras/atualizar_status', class: "form-status") do %>
            <%= hidden_field_tag :id, @compra.id%>

            <div class="fieldset">
                <%= select_tag(:status, options_for_select(["Solicitado","Pagamento aprovado", "Faturado","Em rota", "Entregue"], @compra.status), { prompt: "Status", :class => "select", :required => true }) %>
            </div>
            <div class="actions">
                <%= submit_tag 'Atualizar', class: "action -update" %>
            </div>
        <% end %>
    </div>
</div>

app/views/compras/_edit_form.html.erb
<div class="checkout-products">
    <ul class="list">
        <%@valor_total = 0%>
        <% @produtos.each do |produto| %>
            <li class="product">
                <div class="minimal-details">
                    <div class="image">
                        <span class="qty"><%= produto.quantidade%></span>
                        <%=  image_tag produto.produto.foto, class: "img", alt: "Imagem do produto" %>
                    </div>

                    <div class="attributes">
                        <h3 class="name"><%= produto.produto.nome %></h3>
                    </div>
                    <% @total = produto.quantidade.to_i*produto.produto.preco.to_f %>
                    <div class="price">
                        <span class="subtotal">R$ <%= produto.produto.preco.blank? ? "0.0" : number_with_precision(produto.produto.preco.blank? ? "0.0" : produto.produto.preco, :precision => 2, separator: ",", :delimiter => '.')%></span>
                    </div>
                </div>
            </li>

            <% @valor_total =  @valor_total + @total %>
        <% end %>

    </ul>
</div>

app/views/compras/_form.html.erb
<%= form_with(model: @compra, local: true, id: "regForm") do |form| %>
    <% if @compra.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

            <ul>
                <% @compra.errors.full_messages.each do |message| %>
                <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="checkout-progress">
        <div class="item -active">
            <span class="progress">
            </span>
            <p class="title">
                Carrinho
            </p>
        </div>

        <div class="item">
            <span class="progress">
            </span>
            <p class="title">
                Entrega
            </p>
        </div>

        <div class="item">
            <span class="progress">
            </span>
            <p class="title">
                Confirmação
            </p>
        </div>

        <div class="item">
            <span class="progress">
            </span>
            <p class="title">
                Pagamento
            </p>
        </div>
    </div>

    <div class="checkout-wizard">
        <div class="wrapper">
            <div class="tab">
                <h2 class="title">Quantidade de itens: <%= @produtos.count %></h2>
                <div class="summary-container">
                    <%@valor_total = 0%>
                    <%if params[:action] != "edit"%>
                        <div class="checkout-products">
                            <ul class="list">
                                <%@valor_total = 0%>
                                <% @produtos.each do |produto| %>
                                    <li class="product">
                                        <div class="minimal-details">
                                            <div class="image">
                                                <span class="qty"><%= produto[:quantidade]%></span>
                                                <%=  image_tag produto[:produto].foto, class: "img", alt: "Imagem do produto" %>
                                            </div>

                                            <div class="attributes">
                                                <h3 class="name"><%= produto[:produto][:nome] %></h3>
                                            </div>
                                            <% @total = produto[:quantidade].to_i*produto[:produto][:preco].to_f %>
                                            <div class="price">
                                                <span class="subtotal">R$ <%= produto[:produto][:preco].blank? ? "0.0" : number_with_precision(produto[:produto][:preco].blank? ? "0.0" : produto[:produto][:preco], :precision => 2, separator: ",", :delimiter => '.')%></span>
                                            </div>
                                        </div>
                                    </li>

                                    <% @valor_total =  @valor_total + @total %>
                                <% end %>

                            </ul>
                        </div>
                    <%else%>
                        <%= render 'edit_form' %>
                    <%end%>

                    <div class="heading">
                        <h2 class="title">Subtotal</h2>
                        <h2 class="price">
                            R$ <%= @valor_total.blank? ? "0.0" : number_with_precision(@valor_total.blank? ? "0.0" : @valor_total, :precision => 2, separator: ",", :delimiter => '.')%>
                        </h2>
                    </div>
                </div>
                <%= form.hidden_field :valor_total, value: @valor_total + 10%>
            </div>
            <div class="tab">
                <h1 class="legend">Informações para entrega</h1>

                <fieldset class="fieldset -cep">
                    <%= form.label :cep, "CEP", class: "label" %>
                    <%= form.text_field :cep, class: "input", placeholder: "60000-000", maxlength: 9, required: true %>
                </fieldset>

                <fieldset class="fieldset -bairro">
                    <%= form.label :bairro, "Bairro", class: "label" %>
                    <%= form.text_field :bairro, class: "input", required: true %>
                </fieldset>

                <fieldset class="fieldset -address">
                    <%= form.label :endereco, "Endereço", class: "label" %>
                    <%= form.text_field :endereco, class: "input", required: true %>
                </fieldset>

                <fieldset class="fieldset -city">
                    <%= form.label :cidade, "Cidade", class: "label" %>
                    <%= form.text_field :cidade, class: "input", required: true %>
                </fieldset>

                <fieldset class="fieldset -estado">
                    <label class="label" for="estado">
                        Estado:
                    </label>
                    <%= form.select :estado,[["Acre"], ["Alagoas"], ["Amapá"], ["Amazonas"], ["Bahia"], ["Ceará"], ["Distrito Federal"], ["Espirito Santo"], ["Goiás"], ["Maranhão"], ["Mato Grosso"], ["Mato Grosso do sul"], ["Minas Gerais"], ["Pará"], ["Paraíba"], ["Paraná"], ["Pernambuco"], ["Piauí"], ["Rio de Janeiro"], ["Rio Grande do Norte"], ["Rio Grande do Sul"], ["Rondônia"], ["Roraima"], ["Santa Catarina"], ["São Paulo"], ["Sergipe"], ["Tocantins"]], {prompt: "Selecione um Estado"}, class: "select", :required => true %>
                </fieldset>
            </div>
            <div class="tab">
                <h1 class="legend">Confirmar dados</h1>

                <div class="summary-container">
                    <div class="info">
                        <h2 class="title">Subtotal</h2>
                        <h2 class="price">R$ <%= @valor_total.blank? ? "0.0" : number_with_precision(@valor_total.blank? ? "0.0" : @valor_total, :precision => 2, separator: ",", :delimiter => '.')%></h2>
                    </div>

                    <div class="info">
                        <h2 class="title">Frete</h2>
                        <h2 class="price">R$10,00</h2>
                    </div>

                    <div class="info">
                        <h2 class="title">Total</h2>
                        <h2 class="price">R$ <%= @valor_total.blank? ? "0.0" : number_with_precision(@valor_total.blank? ? "0.0" : @valor_total + 10, :precision => 2, separator: ",", :delimiter => '.')%></h2>
                    </div>
                </div>

                <!-- apenas se o usuário for admin -->
                <% if session[:papel_id] == "Administrador" %>
                    <h1 class="legend">Selecione o cliente</h1>
                    <fieldset class="fieldset -cliente">
                        <%= form.select :cliente_id, Usuario.all.collect{|u| [u.nome + " - " + u.email , u.id]}, {:prompt => 'Selecione o Cliente'}, class: "select", :required => true %>
                    </fieldset>
                <% else %>
                    <% cliente = Cliente.find_by(usuario_id: current_usuario.id) %>
                    <%= form.hidden_field :cliente_id, value: cliente.id %>
                <% end %>
            </div>
            <div class="tab">
                <h1 class="legend">Pagamento</h1>

                <div class="payment-container">
                    <div class="payment-forms">
                        <fieldset class="fieldset">
                            <label class="label">Boleto
                                <%= form.radio_button :forma_pagamento, "Boleto", class: "radio", id: "boleto", :checked => true %>
                                <span class="checkmark"></span>
                            </label>
                            <label class="label">Cartão de Crédito
                                <%= form.radio_button :forma_pagamento, "Cartão de Crédito", id: "credit", class: "radio" %>
                                <span class="checkmark"></span>
                            </label>
                        </fieldset>
                    </div>

                    <div class="card-container -visible">
                        <fieldset class="fieldset -card">
                            <%= form.label :numero_cartao, "Número do Cartão", class: "label" %>
                            <%= form.text_field :numero_cartao, class: "input", placeholder: "0000 0000 0000 0000", maxlength: 19 %>
                        </fieldset>

                        <fieldset class="fieldset -name">
                            <%= form.label :nome_titular, "Nome do titular", class: "label" %>
                            <%= form.text_field :nome_titular, class: "input" %>
                        </fieldset>

                        <br />

                        <fieldset class="fieldset -expire">
                            <%= form.label :data_validade, "Data de validade", class: "label" %>
                            <%= form.text_field :data_validade, class: "input", placeholder: "00/00", maxlength: 5 %>
                        </fieldset>

                        <fieldset class="fieldset -cvv">
                            <%= form.label :cvv, "CVV", class: "label" %>
                            <%= form.text_field :cvv, class: "input", placeholder: "000", maxlength: 3 %>
                        </fieldset>
                    </div>

                    <div class="boleto-container">
                        <div class="actions">
                            <a class="action -download" href="<%=image_url('boleto.pdf')%>" download>
                                <i class="fas fa-download"></i> Baixar Boleto
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="actions">
                <button type="button" class="action -prev" id="prev_button">Voltar</button>
                <button type="button" class="action -next" id="next_button">Próximo</button>
                <%= form.submit "Concluir compra", class: "action -finish", id: "finish_button" %>
            </div>
        </div>
    </div>
<% end %>

app/views/compras/_relatorio_cliente.html.erb
<div class="info-table -relatoriocompras" id="lista_cliente">
    <table class="table">
        <thead>
            <tr class="table-heading">
                <th class="item -compra">Cliente ID</th>
                <th class="item -name">Nome do cliente</th>
                <th class="item -email">Email do cliente</th>
                <th class="item -id">Quantidade de compras</th>
            </tr>
        </thead>

        <tbody class="table-info">
            <% @compras_cliente.each do |cliente, quantidade| %>
            <tr class="list">
                <td class="item -compra" data-th="Cliente ID"><%= cliente %></td>
                <% dados_cliente = Cliente.find(cliente) %>
                <td class="item -name" data-th="Nome"><%= dados_cliente.usuario.nome %></td>
                <td class="item -email" data-th="Email"><%= dados_cliente.usuario.email %></td>
                <td class="item -qty" data-th="Quantidade de compras"><%= quantidade %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/compras/checkout.html.erb
<%= render 'form', compra: @compra %>

app/views/compras/edit.html.erb
<div class="form-container -compra">
    <div class="wrapper">
        <div class="heading">
            <h1 class="legend">Editando compra</h1>
        </div>

        <%= render 'atualizar_status'%>

        <%= render 'form', compra: @compra %>

        <div class="actions">
            <%= link_to 'Ver compra', compra_path, class: "action -show" %>
            <%= link_to '<i class="fas fa-reply"></i> Voltar'.html_safe, compras_path, class: "action -back" %>
        </div>
    </div>
</div>

app/views/compras/index.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="container-info -compras">
    <div class="heading">
        <h1 class="title">Compras</h1>
    </div>

    <div class="info">
        <%= link_to '<i class="fas fa-shopping-cart"></i> Compra presencial'.html_safe, catalogo_produtos_path, class: "link" %>

        <p class="text">
            Com a compra presencial, você pode realizar a compra normalmente pelo cliente,
            escolhendo os produtos e apenas inserindo os dados do mesmo, informando no final o e-mail.
        </p>
    </div>

    <div class="info">
        <%= link_to '<i class="fas fa-calendar-week"></i> Relatório de compras'.html_safe, relatorio_compras_path, class: "link" %>

        <p class="text">
            Acesse o relatório de compras para acessar o total de compras por cliente em um determinado período ou o total de compras por dia
        </p>
    </div>

    <div class="wrapper">
        <div class="info-table -compras">
            <table class="table">
                <thead>
                    <tr class="table-heading">
                        <th class="item -name">Nome do cliente</th>
                        <th class="item -email">Email do cliente</th>
                        <th class="item -datetime">Data/Hora da compra</th>
                        <th class="item -status">Status</th>
                        <th class="item -total">Valor total</th>
                        <th class="item -produtos">Produtos da compra</th>
                        <th class="item -actions"></th>
                        <th></th>
                    </tr>
                </thead>

                <tbody class="table-info">
                    <% @compras.each do |compra| %>
                    <tr class="list">
                        <td class="item -name" data-th="Nome">
                            <%= compra.cliente.usuario.nome %>
                        </td>
                        <td class="item -email" data-th="Email">
                            <%= compra.cliente.usuario.email %>
                        </td>
                        <td class="item -datetime" data-th="Data/Hora">
                            <%= compra.data.strftime("%d/%m/%Y") %> - <%= compra.hora.strftime("%H:%M") %>
                        </td>
                        <td class="item -status" data-th="Status">
                            <%= compra.status %>
                        </td>
                        <td class="item -total" data-th="Total">
                            R$ <%= number_with_precision(compra.valor_total, :precision => 2, separator: ",", :delimiter => '.')%>
                        </td>
                        <td class="actions -produtos" data-th="Produtos">
                            <%= link_to 'Ver produtos', produtos_compras_path(compra_id: compra.id), class: "action -underlined -view" %>
                        </td>
                        <td class="actions" data-th="Ações">
                            <%= link_to 'Ver', compra_path(compra), class: "action -underlined -view" %>
                            <%= link_to 'Editar', edit_compra_path(compra), class: "action -underlined -edit" %>
                            <%= link_to 'Apagar', compra, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "action -underlined -delete" %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/compras/minhas_compras.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="container-info -minhascompras">
    <div class="heading">
        <h1 class="title">Minhas compras</h1>
    </div>

    <div class="wrapper">
        <div class="info-table -minhascompras">
            <table class="table">
                <thead>
                    <tr class="table-heading">
                        <th class="item -total">Valor total</th>
                        <th class="item -pagamento">Forma de pagamento</th>
                        <th class="item -datetime">Data/Hora da compra</th>
                        <th class="item -endereco">Endereço</th>
                        <th class="item -actions"></th>
                        <th></th>
                    </tr>
                </thead>

                <tbody class="table-info">
                    <% @compras.each do |compra| %>
                    <tr class="list">
                        <td class="item -total" data-th="Valor total (R$)">
                            R$ <%= number_with_precision(compra.valor_total, :precision => 2, separator: ",", :delimiter => '.')%>
                        </td>
                        <td class="item -pagamento" data-th="Forma de pagamento">
                            <%= compra.forma_pagamento %>
                        </td>
                        <td class="item -datetime" data-th="Data/Hora da compra">
                            <%= compra.data.strftime("%d/%m/%Y") %> - <%= compra.hora.strftime("%H:%M") %>
                        </td>
                        <td class="item -endereco" data-th="Endereço"><%= compra.endereco %></td>
                        <td class="actions" data-th="Ações">
                            <%= link_to 'Ver detalhes', compra_path(compra), class: "action -underlined -view" %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<%if !notice.blank?%>
    <p id="notice"><%= notice %></p>
<% end %>

<div class="info-container -compra">
	<div class="heading">
		<h1 class="title">Detalhes da compra</h1>
	</div>

	<div class="wrapper">
		<div class="info-box -compra">
			<div class="content">
                <p class="item -name">
                    <strong>Nome do cliente:</strong> <%= @compra.cliente.usuario.nome %>
                </p>
                <p class="item -datetime">
                    <strong>Compra realizada em:</strong> <%= @compra.data.strftime("%d/%m/%Y") %> - <%= @compra.hora.strftime("%H:%M") %>
                </p>
                <p class="item -endereco">
                    <strong>Endereço:</strong> <%= @compra.endereco %>
                </p>
                <p class="item -bairro">
                    <strong>Bairro:</strong> <%= @compra.bairro %>
                </p>
                <p class="item -city">
                    <strong>Cidade:</strong> <%= @compra.cidade %>
                </p>
                <p class="item -estado">
                    <strong>Estado:</strong> <%= @compra.estado %>
                </p>
                <p class="item -status">
                    <strong>Status:</strong> <%= @compra.status %>
                </p>
                <p class="item -status">
                    <strong>Forma de pagamento:</strong> <%= @compra.forma_pagamento %>
                </p>
            </div>

			<div class="actions">
                <% if session[:papel_id] == "Administrador" %>
                    <%= link_to 'Editar', edit_compra_path(1), class: "action -underlined -edit" %>
                <% end %>
                <% if session[:papel_id] == "Administrador" %>
                    <%= link_to 'Voltar para a listagem de compras', compras_path, class: "action -underlined -back" %>
                <% end %>
                <% if session[:papel_id] == "Cliente" %>
                    <%= link_to 'Ver todas as compras', minhas_compras_compras_path, class: "action -underlined -back" %>
                <% end %>
			</div>
		</div>
	</div>
</div>

<br>

<div class="container-info -produtoscompras">
    <div class="heading">
        <h1 class="title">Produtos da compra</h1>
    </div>

    <div class="wrapper">
        <div class="info-table -produtoscompras">
            <table class="table">
                <thead>
                    <tr class="table-heading">
                        <th class="item -img"></th>
                        <th class="item -name">Nome do produto</th>
                        <th class="item -qty">Quantidade</th>
                        <th class="item -price">Preço unitário</th>
                        <th class="item -subtotal">Subtotal</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody class="table-info">
                    <% @produtos_compras.each do |produto_compra| %>
                    <tr class="list">
                        <td class="item -img" data-th="Imagem do produto">
                            <%=  image_tag produto_compra.produto.foto, class: "img", alt: "Imagem do produto" %>
                        </td>
                        <td class="item -name" data-th="Nome do produto"><%= produto_compra.produto.nome %></td>
                        <td class="item -qty" data-th="Quantidade"><%= produto_compra.quantidade %></td>
                        <td class="item -price" data-th="Preço unitário">R$ <%=  produto_compra.produto.preco.blank? ? "0.0" : number_with_precision(produto_compra.produto.preco.blank? ? "0.0" :  produto_compra.produto.preco, :precision => 2, separator: ",", :delimiter => '.')%></td>
                        <% subtotal = produto_compra.quantidade.to_i*produto_compra.produto.preco.to_f %>
                        <td class="item -subtotal" data-th="Subtotal">R$ <%= number_with_precision(subtotal, :precision => 2, separator: ",", :delimiter => '.')%></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>

        <div class="final-info">
            <p class="item -frete">Frete fixo: R$ 10,00</p>
            <p class="item -total">Total: R$ <%= number_with_precision(@compra.valor_total, :precision => 2, separator: ",", :delimiter => '.')%></p>
        </div>
    </div>
</div>