config/routes.rb
Rails.application.routes.draw do
    resources :produtos_compras
    resources :categorias_produtos

    resources :compras do
        collection do
            get 'minhas_compras'
            get 'checkout'
            get 'relatorio'
            post 'cart_save'
            get 'buscar_diario'
            get 'buscar_cliente'
            match 'atualizar_status', via: [:get, :post]
        end
    end

    # post '/compras/cart_save', to: 'compras#cart_save'

    resources :categorias

    resources :produtos do
        collection do
            get 'catalogo'
            match 'view', via: [:get, :post]
        end
    end

    resources :clientes do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
        end
    end
    resources :admins do
        collection do
            match 'view', via: [:get, :post]
            match 'criar', via: [:get, :post]
            match 'editar', via: [:get, :post]
            match 'atualizar', via: [:get, :post]
            match 'excluir', via: [:get, :post]
            get 'private_route'
        end
    end

    devise_for :usuarios

    root to: 'produtos#catalogo'
end

app/views/layouts/_menu.html.erb
<header class="page-header">
    <div class="content">
        <span data-action="toggle-nav" class="action -toggle">
        </span>

        <%= link_to root_path, class: "logo" do %>
            <h1 class="title">
                <i class="fas fa-tags"></i>
                Ecommerce
            </h1>
        <% end %>

        <nav class="menu-navigation">
            <div class="header-profile -logged">
                <div class="header">
                    <div class="photo">
                        <%= image_tag "user-placeholder.png", class: "img", alt: "User profile photo" %>
                    </div>
                    <div class="text">

                        <h3 class="note">
                            Olá,
                            <% if !current_usuario.blank? %>
                                <span class="name"><%= current_usuario.nome %></span>
                            <% else %>
                                <span class="name">visitante</span>
                            <% end %>
                        </h3>

                        <% if !current_usuario.blank? %>
                            <p class="email"><%= current_usuario.email %></p>
                        <% else %>
                            <div class="info">
                                <%= link_to 'Entre', usuario_session_path, class: "link" %>
                                <span>para aproveitar as ofertas!</span>
                            </div>
                        <% end %>
                    </div>
                </div>
                <% if !current_usuario.blank? %>
                    <div class="account-links">
                        <ul class="list">
                            <li class="item">
                                <%= link_to 'Ver Perfil', edit_usuario_registration_path, class: "link -underlined"%>
                            </li>
                        </ul>
                    </div>
                <% end %>
            </div>
            <ul class="list">
                <% if session[:papel_id] == "Administrador" %>
                    <li class="menu-item">
                        <%= link_to 'Categorias', categorias_path, class: "link" %>
                    </li>

                    <li class="menu-item">
                        <%= link_to 'Produtos', produtos_path, class: "link" %>
                    </li>

                    <li class="menu-item">
                        <%= link_to 'Administradores', admins_path, class: "link" %>
                    </li>

                    <li class="menu-item">
                        <%= link_to 'Clientes', clientes_path, class: "link" %>
                    </li>

                    <li class="menu-item">
                        <%= link_to 'Compras', compras_path, class: "link" %>
                    </li>
                <% end %>
            </ul>
            <% if !current_usuario.blank? %>
                <div class="menu-bottom">
                    <div class="links">
                        <%= link_to 'Sair', destroy_usuario_session_path, :method => :delete, class: "action -underlined -signout" %>
                    </div>
                </div>
            <% end %>
        </nav>

        <div class="user-space -logged">
            <button class="button" id="user_button">
            </button>

            <div class="options">
                <ul class="list">
                    <% if !current_usuario.blank? %>
                        <li class="item"><%= link_to 'Perfil', edit_usuario_registration_path, class: "link -underlined"%></li>
                    <% end %>

                    <% if session[:papel_id] == "Cliente" %>
                        <li class="item"><%= link_to 'Minhas compras', minhas_compras_compras_path, class: "link -underlined"%></li>
                    <% end %>

                    <% if current_usuario.blank? %>
                        <li class="item"><%= link_to 'Login', usuario_session_path, class: "link -underlined" %></li>
                        <li class="item"><%= link_to 'Cadastre-se', new_usuario_registration_path, class: "link -underlined" %></li>
                    <% else %>
                        <li class="item"><%= link_to 'Sair', destroy_usuario_session_path, :method => :delete, class: "link -underlined" %></li>
                    <% end %>
                </ul>
            </div>
        </div>

        <div class="cart-container">
            <button class="button" id="cart_button">
                <span class="counter">0</span>
            </button>

            <%= render 'produtos/cart' %>
        </div>
    </div>
</header>

<div class="tocart-alert" id="alert">
    <span>Novo produto adicionado ao carrinho</span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
	<title>Ecommerce</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>

	<%= favicon_link_tag asset_path('favicon.png') %>

	<!-- Main css styles -->
	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

	<!-- Main javascript files -->
	<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="page-view <%= controller_name %>-<%= action_name %>">
	<%= javascript_pack_tag 'masks' %>
	<%= javascript_pack_tag 'cart' %>

	<div class="page-wrapper">
		<%= render 'layouts/menu' %>

		<main class="page-main">
			<%= yield %>
		</main>
	</div>

	<%= javascript_pack_tag 'scripts' %>
	<%= javascript_pack_tag 'checkout' %>
</body>

</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Ecommerce</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= favicon_link_tag asset_path('favicon.png') %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'devise', media: 'all', 'data-turbolinks-track': 'reload'  %>
</head>

<body>
    <div class="devise-main">
        <div class="wrapper">
            <div class="form-box">
                <div class="logo">
                    <%=  image_tag "logo.png", class: "img", alt: "Logo Ecommerce" %> 
                </div>
                <%= yield %>
            </div>
        </div>
    </div>
</body>

</html>